### ISSUE TITLE
Demo fail

### ISSUE THREAD

**Issue by moof2k** [Differential/polymer-demo#21]
I can't get the demo to work. Is it compatible with the latest version of meteor?

```
$ git clone https://github.com/Differential/polymer-demo.git
$ cd polymer-demo/
$ sudo npm install -g bower
$ bower install
$ meteor

[[[[[ ~/src/polymer-demo ]]]]]

=> Started proxy.
=> Started MongoDB.
Vulcanize: Adding all imports...             -
Vulcanize: Adding all imports...             /

.meteor/packages/meteor-tool/.1.1.2.17hn5mu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: EEXIST, mkdir 'src/polymer-demo/.meteor/local/.build134482.build/programs/.build857054.server/app/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/memoizee/node_modules/es6-weak-map/node_modules/es6-iterator/test/'
  at Object.Future.wait (.meteor/packages/meteor-tool/.1.1.2.17hn5mu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper [as mkdir] (.meteor/packages/meteor-tool/.1.1.2.17hn5mu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
...
```

**Comment by tyagiakhilesh** [comment]
What was causing this ? Any clue ?
